---
title: "Shiny Examples"
author: "Matthew Pawliw-Levac"
date: "August 6, 2020"
output: html_document
---

```{r}
library(tidyverse)
```

```{r eval=FALSE}
library(shiny)

server=function(input, output, session) {}
ui=basicPage("the beginning")
shinyApp(ui=ui, server=server)
```

```{r eval=FALSE}
#This is for the second example of the article I'm writing on my understanding of shiny
#This example needs fuildpage, tabs, server and ui elements

# library(tidyverse)

set.seed(11234)
participant <- 1:50
group <- sample(c("A","B","C","D"), 50, replace = TRUE)
score1 <- sample(c(50:100,60:90,70:80),50, replace = TRUE)
score2 <- sample(c(1:100),50,replace = TRUE)

df <- data.frame(participant,group,score1,score2)

ui <- fluidPage(
 
  titlePanel("Example 2"),     # our title
  sidebarLayout(     #beginning of the sidebar functions (also need sidebarPanel)
    sidebarPanel(    
       sliderInput(inputId = "s1",     #Our Slider arguments start here
                   label = "My Slider",
                   value = 1, 
                   min = 1, 
                   max = 20),
       checkboxGroupInput("groupcheck", #Our checkbox arguments start here
                          label = h3("Groups"), 
                          choices = list("A", "B", "C", "D"),
                          selected = list("A", "B", "C", "D"))
    ),
    
    mainPanel( #This is the main panel
      fluidRow( textOutput("textout1"), "test test test", textOutput("textselection"))
     
                
    )
  )
)

server <- function(input, output, session) { #We have server arguments now
  
  data_Groupcheck <- reactive({ #reactive element to let us better use this later
    input$Groupcheck
  })
  
  df_selected <- reactive({ #reactive element to serve as an intermediary filter
    df %>% 
      filter(group %in% input$groupcheck)
  })
  
  
  output$textout1 <- renderText({ #outputs get used either by other outputs or UI elements; 
    paste0(input$s1, " times 5 is ", input$s1 * 5) #this uses the slider input below
  }) #renderText is how we create dynamic text that can change based on data
  
  output$textselection <- renderText({
    paste0(nrow(df_selected()))
  })
  
}

shinyApp(ui = ui, server = server)
```

```{r, message=FALSE, eval=FALSE}
df %>% 
  #filter %>% 
  mutate(mean_score = (score1+ score2)/2) %>% 
  ggplot(aes(x=mean_score))+
  geom_histogram()+
  labs(title = "mean score histogram",
       x = "mean score",
       y = "count")
  
```











